### ISSUE TITLE
Sentinelhub=3.0.0b1 is slow when downloading images

### ISSUE THREAD

**Issue by PeterFogh** [sentinel-hub/sentinelhub-py#100]
Hi, I'm trying out the new Sentinelhub version (sentinelhub==3.0.0b1 conda-forge package, installed in `py37_v9`) for my pipeline collecting Sentinel 2 L1C images for 100 fields. However, I found the new version really slow compared to the older version (sentinelhub==2.6.0 PIP package installed in `py37_v8`) which I previously used, as shown in the table below.

Fields | dask worker processes | dask worker threads | Conda env | max_threads | Time
-- | -- | -- | -- | -- | --
100 | 1 | 20 | py37_v8 | default= os.cpu_count()*5=200 | 13min 51.0s
100 | 20 | 1 | py37_v8 | default= os.cpu_count()*5=200 | 4min 56.8s
100 | 1 | 20 | py37_v9 | 200 | 35min 46.2s
100 | 20 | 1 | py37_v9 | 200 | 42min 36.9s
100 | 1 | 20 | py37_v9 | 32 | 31 min
100 | 20 | 1 | py37_v9 | 32 | 41min 30.7s
100 | 1 | 20 | py37_v9 | 10 | 52min 16.7s

**NOTE:**

- No cache was used in the runs as the cache folder was deleted between runs.
- My pipeline is executed on a dask cluster, and the columns `dask worker processes` and `dask worker threads` refer to the configuration of the dask cluster, see https://distributed.dask.org/en/latest/worker.html#thread-pool for more details.
- The runs with `py37_v9` use an OAuth client, as sentinelhub==3.0.0b1 offers the use of an OAuth client and prompts a warning if you are not using it.
- The `max_threads` is the argument giving to get_data(), see https://sentinelhub-py.readthedocs.io/en/latest/data_request.html#sentinelhub.data_request.DataRequest.get_data. For the runs with `py37_v8`, the argument was not provided, thus, the default number of threads were used. The Conda environment  `py37_v8` contains Python  3.7 where the default `max_threads` from `ThreadPoolExecutor` is `os.cpu_count*5` as seen here: https://github.com/python/cpython/blob/3.7/Lib/concurrent/futures/thread.py#L127. This results in `max_threads=200`, as our machine has 40 hyperthreaded cores.

**Question: Do you have any idea why 3.0.0b1 is so much slower?**

**Comment by AleksMat** [comment]
Yes, in `3.0.0b1` we tried to implement a "smart" rate limit algorithm that would collect information about policy buckets and try to predict when to make next request according to current bucket capacities and estimated frequency of downloads. This way we wanted to avoid hitting rate limit on service too often. However, it turned out the algorithm was too careful and in some cases significantly slowing down the download process.

Now in `3.0.0` we completely simplified the algorithm. The new version now only checks it the rate limit on the service has been hit and waits the recommended amount of time. This way it does not slow down the download process at all but also hits the rate limit much more often.

Our plan is now to wait for a few months to see if the new algorithm works well and if the service is being hit by too many rate-limited requests. According to that, we might further adjust the algorithm.

Thanks for this nice benchmark. It was very helpful when trying to debug the old version of the algorithm. I'm closing this issue for now, but feel free to re-open if you experience any problems with the new version.
