### ISSUE TITLE
Better handling of config.json file

### ISSUE THREAD

**Issue by mlubej** [sentinel-hub/sentinelhub-py#139]
This was mentioned already several times, just wanted to put down a ticket so that we don't lose track of this.

The `config.json` template file for storing credentials is a part of the repo. When we download the repo and change this file, it tracks the changes. Instead of this, it would be preferred if the file is ignored by GIT so that I can focus on actual changes in the development process and so that I don't accidentally delete/overwrite my credentials when reverting the changes.

The `.json` format is in the `.gitignore`, but it's ignored because this file is already in the repo. Not sure what the best solution is. Perhaps an auto-generated template file when it's first called or something.

**Comment by AleksMat** [comment]
I was thinking about the following solution:

The file `config.json` doesn't have to be committed in the repository. It can be automatically generated by `SHConfig` class when you install the package. This way `.gitignore` will correctly ignore `config.json`. The only difference will be that in case you would want to manually change some parameters in `config.json` you'll first have to install the package in order to create the config file.

**Comment by mlubej** [comment]
I think the solution you propose is completely fine:

- if the package is manually cloned, one has to install it anyway to use it
- if the package is installed directly from pip, it's likely being used by a non-technical user and the credentials will be likely set in via the `SHConfig` in the notebook. Otherwise, the location is relatively easy to find. 

Perhaps we could put a message pointing to the config file after the package is installed?
