### ISSUE TITLE
[HELP] Set up AWS region in config.json

### ISSUE THREAD

**Issue by i21510** [sentinel-hub/sentinelhub-py#187]
Hi,

Is it possible to set up the AWS region in config.json? If so, what is the key that should be used? In my current setup, SentinelHub is using environment variable AWS_DEFAULT_REGION, but I would like to change the env variable to a different region and set up eu-central-1 for SentinelHub in config.json.

thanks

**Comment by AleksMat** [comment]
Hi @i21510,

This is not possible to do in config.json, although it is something that could be supported in the future. Any pull requests regarding this are welcome.

There is however an alternative solution. Instead of setting credentials in `config.json` you can use `awscli` tool to configure them globally in `~/.aws` folder. It will also allow you configure the region. If there will be no credentials in `config.json` then `boto3` package, which is used in the background of `sentinelhub-py`, will take credentials from `~/.aws` folder.
