### ISSUE TITLE
Newest sentinelhub version is not found on anaconda

### ISSUE THREAD

**Issue by DonjetaR** [sentinel-hub/sentinelhub-py#224]
I see that the newest version of `eo-learn=0.10.1` is on anaconda but it is only compatible with the newest changes in `sentinelhub=3.4.2` which is found in PyPI. Would you be kind to build a conda package with `sentinelhub=3.4.2`?

**Comment by AleksMat** [comment]
Hi @DonjetaR,

Our developers are currently not among maintainers of [`sentinelhub` Conda Forge release repository](https://github.com/conda-forge/sentinelhub-feedstock). Due to lack of time we so far only took the responsibility of maintaining releases to PyPI ourselves.

Therefore I recommend checking with the maintainers of the Conda Forge repo. The reason why the latest builds (e.g. https://github.com/conda-forge/sentinelhub-feedstock/pull/18) are failing is that we added `tqdm` on the list of package dependencies, therefore the [recipe file](https://github.com/conda-forge/sentinelhub-feedstock/blob/master/recipe/meta.yaml) would have to be updated accordingly.
