### ISSUE TITLE
AttributeError: module 'requests' has no attribute 'ConnectTimeout'

### ISSUE THREAD

**Issue by saanasum** [sentinel-hub/sentinelhub-py#24]
Hi,

many thanks for providing this very useful tool. 

When working through the tutorial (http://sentinelhub-py.readthedocs.io/en/latest/examples/ogc_request.html) I get the error message: `"AttributeError: module 'requests' has no attribute 'ConnectTimeout'"` when requesting the following:
```

wms_bands_request = WmsRequest(layer='ALL_BANDS',
                               bbox=betsiboka_bbox,
                               time='latest',
                               width=512, height=856,
                               image_format=MimeType.TIFF_d32f,
                               instance_id=INSTANCE_ID)

wms_bands_img = wms_bands_request.get_data()
```

What might be the reason for it? I have a trial account ID.

Many thanks
s.

**Comment by saanasum** [comment]
solved: 

I followed https://github.com/saanasum/sentinelhub-py/blob/master/examples/ogc_request.ipynb and defined an new layer via https://apps.sentinel-hub.com/configurator/#/ using the custom script: return [B01,B02,B03,B04,B05,B06,B07,B08,B8A,B09,B10,B11,B12] in the layer setting window.

**Comment by AleksMat** [comment]
Great that you managed to solve the problem.

About the weird `AttributeError` you got - the reason is that your `requests` Python package is a bit outdated. Attribute `ConnectError` was added to `requests` in 2014 somewhere around version `2.3.0`.

Solution for that is to upgrade the `requests` package with
`pip install requests --upgrade`
or
`pip install sentinelhub --upgrade`
which will upgrade all packages required for `sentinelhub`

**Comment by saanasum** [comment]
Thanks. I did so.
