### ISSUE TITLE
[HELP] Download empty scenes

### ISSUE THREAD

**Issue by AdrienWehrle** [sentinel-hub/sentinelhub-py#256]
Hi everyone,

when I run a `SentinelHubRequest` on a scene that is not available (e.g. no scene in the bounding box at a given date), I get output matrices set to zero. I would like to know if there is a way to exclude those scenes in the request itself, so I don't have to run checks afterwards to disregard them (or maybe I currently need those checks because I don't use the method properly?). I wrote a wrapper for `SentinelHubRequest` (initially for myself, but recently released it), and currently use `get_data` to check for those empty scenes (the checks are relatively silly at the moment):
https://github.com/AdrienWehrle/earthspy/blob/e981dd670c8551a0e3b680969aa461a2d5d8c42c/earthspy/earthspy.py#L746

and then save with `save_data`, which is [purely inefficient](https://github.com/AdrienWehrle/earthspy/issues/28) as I download the data twice...

Thank you a lot in advance for your help! (And any feedback on the [earthspy](https://github.com/AdrienWehrle/earthspy) package, which is WIP, is much appreciated and very helpful!)

**Comment by AleksMat** [comment]
Hi @AdrienWehrle,

I recommend using [Catalog API](https://docs.sentinel-hub.com/api/latest/api/catalog/) which is our main service to search for available data. Examples of how to use it within `sentinelhub-py` are [here](https://sentinelhub-py.readthedocs.io/en/latest/examples/data_search.html#Sentinel-Hub-Catalog-API) and I especially recommend checking the [example](https://sentinelhub-py.readthedocs.io/en/latest/examples/data_search.html#Combine-Catalog-API-with-Process-API) that combines Catalog API and Process API in order to get all available data for a given time interval.

Good luck with `earthspy`!

**Comment by AdrienWehrle** [comment]
Hi @AleksMat ! Thank you a lot, this is exactly what I needed!

**Comment by hmtrii** [comment]
Hi there, I wonder which is the filter command that checks data is available for a Box or output matrices are not set to zero? The example only shows the filter for cloud coverage.
Thanks advance!
@AdrienWehrle @AleksMat

**Comment by AdrienWehrle** [comment]
Hi @hmtrii ! You can find an example addressing this in this method: https://github.com/AdrienWehrle/earthspy/blob/main/earthspy/earthspy.py#L208 !

**Comment by hmtrii** [comment]
Thank @AdrienWehrle, I recognize it does not need any filer command :smile:
