### ISSUE TITLE
ReferenceError: B10 is not defined"

### ISSUE THREAD

**Issue by PeterFogh** [sentinel-hub/sentinelhub-py#27]
Hi. Why does the following code produce the error, and why can I not use B10 in the data processing script?

```
bbox = BBox([start_min_latitude,
            start_min_longitude, 
            start_min_latitude + 500, 
            start_min_longitude - 500], 
            crs=CRS.UTM_32N)
all_bands_script = 'return [B01, B02, B03, B04, B05, B06, B07, B08, B8A, B09, B10, B11, B12]'
req = OgcRequest(data_source=DataSource.SENTINEL2_L2A,
                 service_type=ServiceType.WCS,
                 custom_url_params={CustomUrlParam.EVALSCRIPT: all_bands_script},
                 size_x='10m',
                 size_y='10m', 
                 bbox=bbox, 
                 time='2017-12-09',
                 instance_id=INSTANCE_ID,
                 layer=S2_LAYER,
                 image_format=FILE_TYPE)
req.get_data()
```
the returned error is:
```
Server response: "Failed to evaluate script! 
ReferenceError: B10 is not defined" 
```

**Comment by AleksMat** [comment]
Good question. Short answer - it is because ESA doesn't produce band B10 in their Sentinel-2 L2A products. Therefore also Sentinel Hub services don't provide it.

Band B10 is a cirrus band and and mostly contains data about clouds in the upper atmosphere. Because L2A products are atmospherically corrected the resulting B10 band would probably be completely empty. So it wouldn't make sense to include it into the product.

You can check more about L2A products in [ESA product definition](https://sentinel.esa.int/documents/247904/685211/S2+L2A+Product+Definition+Document/2c0f6d5f-60b5-48de-bc0d-e0f45ca06304).
