### ISSUE TITLE
tileInfo error on AwsTileRequest sentinel-hub download

### ISSUE THREAD

**Issue by olivierpfrancois** [sentinel-hub/sentinelhub-py#322]
I am having a new error on my attempts to download sentinel images using sentinelhub. Whatever the image, even some I downloaded in the past, I get the following error:
`sentinelhub.exceptions.DownloadFailedException: Failed to download from:`
`https://roda.sentinel-hub.com/sentinel-s2-l1c/tiles/17/M/RU/2021/6/10/1/tileInfo.json`
`with HTTPError:`
`404 Client Error: Not Found for url: https://roda.sentinel-hub.com/sentinel-s2-l1c/tiles/17/M/RU/2021/6/10/1/tileInfo.json`
`Server response: ""`

The image bands download properly, but then I get that error that blocks further downloads. This is the case even though I am not trying to download the metadata.

The code snippet is as follows, and used to work until a month ago when I last used it without any problem.

`for aws_index in range(10):`
`    #Create a request`
`    request = AwsTileRequest(tile=t, time=date, `
`        aws_index=aws_index, bands=bands, `
`        data_folder=outDir, `
`        data_collection=data_collection, `
`        safe_format=safe_format, `
`        metafiles=None)`

`        #Trigger the download`
`        request.save_data(redownload=False)`

Again, I get the error with or without the metafiles argument in the function.

Where is the new error coming from?

**Comment by devisperessutti** [comment]
Hi @olivierpfrancois,

It looks that for the example you provided there is only one product available 

https://roda.sentinel-hub.com/sentinel-s2-l1c/tiles/17/M/RU/2021/6/10/

which you probably download correctly when `aws_index=0`, https://roda.sentinel-hub.com/sentinel-s2-l1c/tiles/17/M/RU/2021/6/10/0/

You get the error when `aws_index > 0` because there are no additional products.

**Comment by olivierpfrancois** [comment]
Thank you, I managed to run it with that.
