### ISSUE TITLE
[HELP] Sentinel-3 altimetry SRAL/MWR

### ISSUE THREAD

**Issue by AdrienWehrle** [sentinel-hub/sentinelhub-py#327]
Hi everyone,

I can't find Sentinel-3 SRAL/MWR altimetry anywhere in the data collections, so I am assuming it is not available. Am I correct? If so, any plans for its inclusion in your services?

Thank you a lot in advance for your help!

**Comment by zigaLuksic** [comment]
Hi @AdrienWehrle 
The available collections of Sentinel Hub service can be found [here](https://docs.sentinel-hub.com/api/latest/data/), and since they don't (yet) provide S3 SRAL/MWR data we cannot do it in `sentinelhub-py` either.

If you want to know when/if it will be available you should ask on the [forum](https://forum.sentinel-hub.com/).

**Comment by AdrienWehrle** [comment]
Hi @zigaLuksic!

Thank you a lot for your answer! :+1:
