### ISSUE TITLE
Failed to load resource: the server responded with a status of 503 (Service Unavailable)

### ISSUE THREAD

**Issue by achyutjoshi** [sentinel-hub/sentinelhub-py#50]
Hi,

I have been trying to fetch data using WMS, however, I get 503 status every time. Can someone help?

EDIT 1: The image returned in a blank white image. Also, server still returns a 503 status

**Comment by gmilcinski** [comment]
Looking at the error logs on the server to the calls (probably) coming to your two instances I do not see any 503 error. There were however 4XX error, related to requesting layer, which does not exist in your configuration. Service did not have any operational issues in the past hours either.
Could you be a bit more specific on what you tried to do so that we can investigate more?

**Comment by achyutjoshi** [comment]
Thanks for getting back quickly. Appreciate it.

I am using Development Seed's[ Label-Maker](https://github.com/developmentseed/label-maker) to create labelled training data. The query I am making is something like this - 

https://services.sentinel-hub.com/ogc/wms/[INSTANCE_ID]?service=WMS&request=GetMap&layers=1_TRUE_COLOR&format=image%2Fpng&width=256&height=256&srs=EPSG%3A3857&bbox=72.37,22.5,72.9,23.5

And it returns a blank white image on my browser with a 503 status. Attached is the image for your reference - 

![screen shot 2018-10-28 at 11 57 42 am](https://user-images.githubusercontent.com/6535360/47618390-ee2baa00-daa8-11e8-9b26-fa103c0ef029.png)

**Comment by gmilcinski** [comment]
You have SRS set to EPSG:3857, but your coordinates are likely in EPSG:4326. You need to change one or another.
Check also this post related to possible further complexities with EPSG:4326:
https://www.sentinel-hub.com/faq/why-result-different-when-i-am-using-wms-or-wcs-when-coordinate-system-epsg4326

**Comment by achyutjoshi** [comment]
Hi! 

This makes sense. Thank you for helping. 

On a side note, can this be incorporated as an error handler so that it becomes easier if anyone queries using a wrong coordinate system?

**Comment by gmilcinski** [comment]
This is not really trivial as there are tens (hundreds) of different coordinate systems.
Generally there is a big mess with different CRS-es in different OGC standards. We are working on proprietary, non-OGC-compliant API to make it a bit easier.

**Comment by AleksMat** [comment]
Hi @achyutjoshi,

I have 2 explanations about this issue:

- When you call WMS request in your browser, the browser actually executes 2 calls to Sentinel Hub services. The first one is to your intended URL (written above) and it should be successful (HTTP status 200). The second one is an automatic request to https://services.sentinel-hub.com/favicon.ico. The browser thinks you are requesting a webpage and tries to get its icon. Because there is no icon at that address the request produces HTTP error 503. I think this is the one you reported. Fortunately it doesn't affect the real request in any way. 
Chrome debug tool is more informative about the error:

![error503](https://user-images.githubusercontent.com/9626750/47619793-c5c0a180-dae2-11e8-8aba-d07bb497d54a.png)

- Popular Web Mercator CRS (`EPSG:3857`) is defined for approximate area `(-20037508.3, -20037508.3) x (20037508.3, 20037508.3)`. Therefore your bounding box (`72.37,22.5,72.9,23.5`) was recognized as a valid bounding box, even thought it was intended for `EPSG:4326`. In `EPSG:3857` those coordinates specify some very small area in the Atlantic ocean where there are no Sentinel-2 images. That is why you got an empty image.
Hence in cases like this the services cannot say for sure that the request is invalid and raise an error.

I hope this helps. :)
