### ISSUE TITLE
Convert pixel coordinates to lat, lng

### ISSUE THREAD

**Issue by Spiruel** [sentinel-hub/sentinelhub-py#51]
Without downloading Sentinel images and reading them with the use of another library, eg Rasterio - I am struggling to find an effective way using sentinelhub-py of converting pixel coordinates to latitude and longitude. Can anyone help?

**Comment by AleksMat** [comment]
Hi @Spiruel,

With tools from `sentinelhub-py` you can transform from pixel coordinates (row, column in your image) to `WGS84` via one of the `UTM` coordinate reference systems.

First you need to know which UTM CRS you are working with and a transform vector of your image in that `UTM`. Then you have to use `sentinelhub.pixel_to_utm` function and then `sentinelhub.to_wgs84` function. Their parameters are specified in [documentation](https://sentinelhub-py.readthedocs.io/en/latest/geo_utils.html).

In order to be able to help you further I would probably have to know the following:
Which type of satellite data are you working with? If you are working with Sentinel-2, are you using original tiles provided by ESA or images downloaded from Sentinel Hub? Do you require a precise transformation for any pixel?

**Comment by AleksMat** [comment]
At the moment `sentinelhub-py` does not support reading geo info from downloaded images. For that we would probably have to add `rasterio`, `gdal` or some similar package as a dependency. However in this case you can get required information . All you need is CRS, coordinates of upper left corner of your image and resolution of your image. 

- If you are using OGC (WMS, WCS) requests I suggest downloading data in `UTM` CRS (it will also improve accuracy of your final result). You can use `sentinelhub.geo_utils.to_utm_bbox` to transform your `BBox` object into a correct `UTM`. To download images with known resolution I also suggest using `WcsRequest` instead of `WmsRequest`.

- If you are downloading data from AWS (i.e. using `AwsProductRequest` or `AwsTileRequest`) you can use parameter `metafiles`. The parameter takes a list of additional metadata files to download. In your case you require `tileInfo.json`. Check this [example](https://roda.sentinel-hub.com/sentinel-s2-l1c/tiles/1/C/CV/2017/1/14/0/tileInfo.json) to see its content and its HTTP address. From `tileOrigin` you can read the required data. Here is a code example how to obtain it:

```Python
from sentinelhub import AwsTileRequest

request = AwsTileRequest(tile='T01CCV', time='2017-01-14', bands=[], metafiles=['tileInfo.json'])
tile_info = request.get_data()[0]
```

**Comment by Spiruel** [comment]
Many thanks for clearing that up!
