### ISSUE TITLE
Get size of download

### ISSUE THREAD

**Issue by aceconhielo** [sentinel-hub/sentinelhub-py#71]
Hello, is there any way to get the size of the total request download before to execute the request??

Thanks

**Comment by AleksMat** [comment]
Hi @aceconhielo,

Unfortunately such option doesn't exist but I agree it might be useful. Some time in next few months we plan to integrate [new Sentinel Hub service API](https://docs.sentinel-hub.com/api/latest/#/API/) into `sentinelhub-py` and with it something like this could maybe become possible.

The closest thing that currently exists is a method [`get_url_list()`](https://sentinelhub-py.readthedocs.io/en/latest/data_request.html#sentinelhub.data_request.DataRequest.get_url_list) which you can call on your instance of data request class, before calling `get_data` or `save_data` methods. This way you can see how many download requests will be made. Since you know the size of your requested images, number of bands and data format you could probably estimate the approximate overall size of the data you are going to download.
