### ISSUE TITLE
conda-forge submission

### ISSUE THREAD

**Issue by Thingus** [sentinel-hub/sentinelhub-py#78]
Hi maintainers
I'm putting a library up on Conda-Forge, and it contains this library as a dependency. Are you alright with my using conda skeleton to submit this repository to conda-forge? I'm happy to list myself as the maintainer, and it includes all references back to this repository.
The library in question:
https://github.com/clcr/pyeo
The conda forge pull request:
https://github.com/conda-forge/staged-recipes/pull/8972

**Comment by AleksMat** [comment]
Hi @Thingus,

Thanks for preparing the recipe for `sentinelhub` and informing us about it. This is something we had on our wish list for a while now but simply couldn't find time to do it ourselves. Therefore we are happy to give you permission to submit the repository to conda-forge.

In order to keep `sentinelhub` recipe up-to-date in the future, we would also like to offer to help you maintain it. At the moment @andrejburja, @iovsn and myself are involved in the process of releasing new versions. If you add us to the list of collaborators we can make sure the recipe will be updated every time we make a new release.

**Comment by Thingus** [comment]
Much appreciated!
I'll merge in the changes you suggested in the pull request.
Part of the assurance process for Conda-forge is to make sure that everyone listed in the skeleton as a maintainer is happy to do it; could you, @andrejburja and @iovsn leave comments in the pull request to that end?

**Comment by AleksMat** [comment]
Excellent, I let  @andrejburja and @iovsn know about this and we will write confirmations today.

**Comment by Thingus** [comment]
Just seen the last confirmation up on the pr, so I'll close this issue
