### ISSUE TITLE
Cannot set "aws_metadata_url" in config.json to an S3 url

### ISSUE THREAD

**Issue by mitch3x3** [sentinel-hub/sentinelhub-py#87]
When I set the `"metadata url"` in `config.json` to `"s3://sentinel-s2-l1c/"`, the URL prefix in the actual download command becomes `"s3://sentinel-s2-l1c/sentinel-s2-l1c/"`.

This looks like an issue in the : `aws.py -> AwsService().get_base_url()` function getting its `force_http` argument set to `True` somewhere upstream.

I've cut out the referenced code and tested it locally and it behaves as expected with the `force_http` argument set to `False`.

If it was just a simple parsing issue I would have submitted a PR, but this appears to be related to some other logic that I don't feel I have the full context to edit.

**Comment by AleksMat** [comment]
This has now been fixed in PR https://github.com/sentinel-hub/sentinelhub-py/pull/103. Now it is possible to change `"aws_metadata_url"` from `"https://roda.sentinel-hub.com"` to `"s3://"` and it will successfully collect metadata directly from s3 instead of proxy roda service.

This will be released in the new version on Monday. Thanks for reporting the issue. :+1:
